### ISSUE TITLE
!sound xxx not working

### ISSUE THREAD

**Issue by Kiritosblade** [sayonari/twitchTransFreeNext#58]
When using !sound lol,
this error appears.
***I have debug enabled***
```
echo: False, !sound lol
Traceback (most recent call last):
  File "twitchio\ext\commands\core.py", line 156, in parse_args
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twitchio\client.py", line 199, in wrapped
  File "twitchTransFN.py", line 191, in event_message
  File "twitchio\ext\commands\bot.py", line 334, in handle_commands
  File "twitchio\ext\commands\bot.py", line 341, in invoke
  File "twitchio\ext\commands\core.py", line 295, in __call__
  File "twitchio\ext\commands\core.py", line 202, in invoke
  File "twitchio\ext\commands\core.py", line 158, in parse_args
twitchio.ext.commands.errors.TwitchCommandError: self or ctx is a required argument which is missing.
```

**Comment by Kiritosblade** [comment]
[https://cdn.discordapp.com/attachments/1032769649571549214/1084308818676170862/image.png](url)
Here's a screenshot to show i do have this lol.mp3 in 'correct'? folder

**Comment by didotb** [comment]
it is an error on the function after an update months ago. I guess it was never fixed.
let me try to fix it for you

**Comment by didotb** [comment]
@Kiritosblade looks like I already fixed this on my own fork.
You can read my PR as well if you wanna know the difference #51 
Or you can also check out @yuniruyuni 's PR if you just want the sound module fixed without the added features I made. #57 

@Kiritosblade 自分のフォークですでに修正したようです。
違いを知りたければ、私のPRも読んでみてください #51 
また、私が作った機能を追加することなく、サウンドモジュールの修正だけを望むなら、@yuniruyuni のPRをチェックすることもできます。#57

**Comment by Kiritosblade** [comment]
This did solve the issue, sorry it took this long to get back to you on this.
